# https://taskfile.dev

version: '3'

vars:
  HOST_PORT: 9000
  TAILSCALE_IP: 100.88.184.87

tasks:
  default:
    desc: Print all available tasks
    cmds:
      - task -a
    silent: true

  up:
    desc: Docker compose up Portainer
    cmds:
      - docker compose up -d

  down:
    desc: Docker compose down Portainer
    cmds:
      - docker compose down

  pull:
    desc: Pull latest version
    cmds:
      - docker compose pull

  tailfwd:
    desc: Forward port to localhost with the help of iphlpsvc [RunAsAdmin]
    cmds:
      - powershell -c Restart-Service iphlpsvc -Force;
      - >-
        netsh interface portproxy set v4tov4
        listenport={{.HOST_PORT}} listenaddress={{.TAILSCALE_IP}}
        connectport={{.HOST_PORT}} connectaddress=127.0.0.1
      - powershell -c Restart-Service iphlpsvc -Force;

  tailfwd:null:
    desc: Delete forwarded port to localhost with the help of iphlpsvc [RunAsAdmin]
    cmds:
      - powershell -c Restart-Service iphlpsvc -Force;
      - >-
        netsh interface portproxy delete v4tov4
        listenport={{.HOST_PORT}} listenaddress={{.TAILSCALE_IP}}
      - powershell -c Restart-Service iphlpsvc -Force;
